# Generated by Django 5.1.1 on 2024-09-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_educationallevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('years_of_experience', models.PositiveIntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='job.domain')),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='job.educationallevel')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='job.quarter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='job.region')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='job.specification')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='job.town')),
            ],
        ),
    ]
