# Generated by Django 5.1.1 on 2024-09-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='from_number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
