# Generated by Django 5.1.1 on 2024-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_forummessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='age',
            field=models.IntegerField(default='20'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2023-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(default='douala', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(default='resumes/placeholder.pdf', upload_to='resumes/'),
        ),
    ]
