# Generated by Django 5.1.1 on 2024-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_networking'),
    ]

    operations = [
        migrations.AddField(
            model_name='networking',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='networking',
            name='facebook',
            field=models.URLField(blank=True, default='https://facebook.com/default-profile', max_length=255),
        ),
    ]
