# Generated by Django 5.1.1 on 2024-09-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_networking_email_networking_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='communications/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
