# Generated by Django 5.1.1 on 2024-09-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_communication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='location',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='resume',
        ),
    ]
