# Generated by Django 5.1.1 on 2024-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_remove_portfolio_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='temp_field',
            field=models.CharField(default='temp', max_length=50),
        ),
    ]
