# Generated by Django 5.1.1 on 2024-09-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_portfolio_temp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='payment_status',
            field=models.CharField(default='not paid', max_length=20),
        ),
    ]
