# Generated by Django 5.1.1 on 2024-09-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='service_rate',
        ),
    ]
