# Generated by Django 5.1.1 on 2024-09-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_remove_contact_service_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
